### ISSUE TITLE
Error Faced while running locally using git cloned

### ISSUE THREAD

**Issue by Redbro1** [pkjmesra/PKScreener#180]
I found 2 errors:
---
one in is in Fetcher.py 

which is like this
`KeyError: 'MAPMYINDIA.NS'` in _fetchStockData()_

---
other one is connection error:

`requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out. (read timeout=10)`

---

- Error logs given below 
- All libraries installed and Python version 3.11.9 in linux

Please address them Devs.
Thanks

```

2024-09-05 23:45:54,856 - PKDevTools - DEBUG - log.py - log - debug - 248
log.py' -  lineno=227 -  function='addHandlers'
PKDevTools: Logging started. Filter:<class 'filter'>


2024-09-05 23:45:56,543 - PKDevTools - DEBUG - log.py - log - debug - 248
globals.py' -  lineno=875 -  function='main'
User Passed args: Namespace(answerdefault='Y', backtestdaysago=None, barometer=False, bot=False, botavailable=False, croninterval=None, download=False, exit=False, forceBacktestsForZeroResultDays=None, intraday=None, monitor=None, maxdisplayresults=None, maxprice=None, minprice=None, options=None, prodbuild=False, progressstatus=None, runintradayanalysis=False, simulate=None, singlethread=False, stocklist=None, systemlaunched=False, testbuild=False, telegram=False, triggertimestamp=1725579956, user=None, log=True, v=False, pipedtitle=None, pipedmenus=None, usertag=None)


2024-09-05 23:46:07,315 - PKDevTools - DEBUG - log.py - log - debug - 248
Fetcher.py' -  lineno=161 -  function='fetchURL'
HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out. (read timeout=10)
Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1314, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1166, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 470, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/PKDevTools/classes/Fetcher.py", line 152, in fetchURL
    response = requestor.get(
               ^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out. (read timeout=10)

2024-09-05 23:46:18,279 - PKDevTools - DEBUG - log.py - log - debug - 248
Fetcher.py' -  lineno=161 -  function='fetchURL'
HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out. (read timeout=10)
Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1314, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1166, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 470, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/PKDevTools/classes/Fetcher.py", line 152, in fetchURL
    response = requestor.get(
               ^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out. (read timeout=10)

2024-09-05 23:46:29,235 - PKDevTools - DEBUG - log.py - log - debug - 248
Fetcher.py' -  lineno=161 -  function='fetchURL'
HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out. (read timeout=10)
Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1314, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1166, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 470, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/PKDevTools/classes/Fetcher.py", line 152, in fetchURL
    response = requestor.get(
               ^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out. (read timeout=10)

2024-09-05 23:46:39,991 - PKDevTools - DEBUG - log.py - log - debug - 248
Fetcher.py' -  lineno=161 -  function='fetchURL'
HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out. (read timeout=10)
Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1314, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1166, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 470, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/PKDevTools/classes/Fetcher.py", line 152, in fetchURL
    response = requestor.get(
               ^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out. (read timeout=10)

2024-09-05 23:46:51,904 - PKDevTools - DEBUG - log.py - log - debug - 248
Utility.py' -  lineno=930 -  function='loadStockData'
Stock data cache file:stock_data_050924.pkl exists ->True


2024-09-05 23:47:07,818 - PKDevTools - DEBUG - log.py - log - debug - 248
Fetcher.py' -  lineno=136 -  function='fetchStockData'
'ASPINWALL.NS'
Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/pkscreener/classes/Fetcher.py", line 115, in fetchStockData
    data = yf.download(
           ^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/yfinance/utils.py", line 104, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/yfinance/multi.py", line 205, in download
    return shared._DFS[ticker]
           ~~~~~~~~~~~^^^^^^^^
KeyError: 'ASPINWALL.NS'

2024-09-05 23:47:07,823 - PKDevTools - DEBUG - log.py - log - debug - 248
PKScanRunner.py' -  lineno=396 -  function='terminateAllWorkers'
Worker terminated!


2024-09-05 23:47:07,829 - PKDevTools - DEBUG - log.py - log - debug - 248
PKScanRunner.py' -  lineno=396 -  function='terminateAllWorkers'
Worker terminated!


2024-09-05 23:47:07,835 - PKDevTools - DEBUG - log.py - log - debug - 248
PKScanRunner.py' -  lineno=396 -  function='terminateAllWorkers'
Worker terminated!


2024-09-05 23:47:07,841 - PKDevTools - DEBUG - log.py - log - debug - 248
PKScanRunner.py' -  lineno=396 -  function='terminateAllWorkers'
Worker terminated!


2024-09-05 23:47:07,843 - PKDevTools - DEBUG - log.py - log - debug - 248
Fetcher.py' -  lineno=135 -  function='fetchStockData'
'SECURKLOUD.NS'
Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/pkscreener/classes/Fetcher.py", line 115, in fetchStockData
    data = yf.download(
           ^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/yfinance/utils.py", line 104, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/yfinance/multi.py", line 205, in download
    return shared._DFS[ticker]
           ~~~~~~~~~~~^^^^^^^^
KeyError: 'SECURKLOUD.NS'

2024-09-05 23:47:07,847 - PKDevTools - DEBUG - log.py - log - debug - 248
PKScanRunner.py' -  lineno=396 -  function='terminateAllWorkers'
Worker terminated!


2024-09-05 23:47:07,852 - PKDevTools - DEBUG - log.py - log - debug - 248
PKScanRunner.py' -  lineno=396 -  function='terminateAllWorkers'
Worker terminated!


2024-09-05 23:47:07,856 - PKDevTools - DEBUG - log.py - log - debug - 248
Fetcher.py' -  lineno=135 -  function='fetchStockData'
'RKDL.NS'
Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/pkscreener/classes/Fetcher.py", line 115, in fetchStockData
    data = yf.download(
           ^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/yfinance/utils.py", line 104, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/yfinance/multi.py", line 205, in download
    return shared._DFS[ticker]
           ~~~~~~~~~~~^^^^^^^^
KeyError: 'RKDL.NS'

2024-09-05 23:47:07,858 - PKDevTools - DEBUG - log.py - log - debug - 248
PKScanRunner.py' -  lineno=396 -  function='terminateAllWorkers'
Worker terminated!


2024-09-05 23:47:07,861 - PKDevTools - DEBUG - log.py - log - debug - 248
PKScanRunner.py' -  lineno=396 -  function='terminateAllWorkers'
Worker terminated!


2024-09-05 23:47:07,867 - PKDevTools - DEBUG - log.py - log - debug - 248
PKScanRunner.py' -  lineno=396 -  function='terminateAllWorkers'
Worker terminated!


2024-09-05 23:47:07,867 - PKDevTools - DEBUG - log.py - log - debug - 248
Fetcher.py' -  lineno=135 -  function='fetchStockData'
'MAPMYINDIA.NS'
Traceback (most recent call last):
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/pkscreener/classes/Fetcher.py", line 115, in fetchStockData
    data = yf.download(
           ^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/yfinance/utils.py", line 104, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hextron/project/pkscreenerpythondir/lib/python3.11/site-packages/yfinance/multi.py", line 205, in download
    return shared._DFS[ticker]
           ~~~~~~~~~~~^^^^^^^^
KeyError: 'MAPMYINDIA.NS'
```

**Comment by pkjmesra** [comment]
@Redbro1 - Did you have these errors while you were running the app normally ? Or did you see these only after you enabled logging?

From the logs, it seems like the later.
Please note that data provider, in this case Yahoo finance, may not necessarily always have that symbol's data. At times it may return null/NaN data or simple not recognise the symbol, for example, MAPMYINDIA, in this case.

Let me know if you saw these without enabling the logs.

**Comment by Redbro1** [comment]
### Problem solved
Thanks for your support I finally figured out the problem. 

The problem seems was I used settings to block fc[.]yahoo[.]com after removed it from blacklist it working pretty fine 


Thanks Regards to Dev team.
